### ISSUE TITLE
2020 Update required before end of season. Or not legal

### ISSUE THREAD

**Issue by CJBuchel** [CurtinFRC/2020-InfiniteRecharge#30]

**Comment by met4000** [comment]
See https://github.com/met4000/2020-InfiniteRecharge/commit/758517485dda04e8f22e23decfa18cb6ea30cc60 (changing the way that WML is included in gradle, and using the WML 2020 update branch)

**Comment by CJBuchel** [comment]
yeee, will do today.... probably
